// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABGWjg-a66ge-fRnHiw4sulTtZHA3bjqs',
    appId: '1:946314436203:android:a9923e0e9becc59e0d1b2e',
    messagingSenderId: '946314436203',
    projectId: 'fire-notes-ce334',
    storageBucket: 'fire-notes-ce334.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWueRSB3KNwYgluBN2_dSM6kVlZ74uk1U',
    appId: '1:946314436203:ios:cf8c7883f8ad01cd0d1b2e',
    messagingSenderId: '946314436203',
    projectId: 'fire-notes-ce334',
    storageBucket: 'fire-notes-ce334.appspot.com',
    androidClientId: '946314436203-3elt98fdf3hqmnnqk96v8shaoabjk4a0.apps.googleusercontent.com',
    iosClientId: '946314436203-m2na4boaahhovaoah8anhovt3qngoh07.apps.googleusercontent.com',
    iosBundleId: 'com.appup.fireNotes',
  );
}
