# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

platform :android do
  desc "Distribute beta version to firebase testers"
  lane :distribute do
      gradle(task: "clean assembleRelease")
      # build_android_app(...)
      # build_android_app is a built-in fastlane action.
      firebase_app_distribution(
          app: "1:946314436203:android:a9923e0e9becc59e0d1b2e",
          testers: "livesince91@gmail.com",
          android_artifact_type: "APK",
          apk_path: "/Users/ameyabhagat/Developer/Flutter/Projects/tutorials/domain driven design/fire_notes/build/app/outputs/flutter-apk/app-release.apk",
          release_notes_file: "/Users/ameyabhagat/Developer/Flutter/Projects/tutorials/domain driven design/fire_notes/release_notes/RELEASE_NOTES.txt",
      )
  end
end